import DeliveryAnalytics from "@/components/DeliveryAnalytics";
import EarningReports from "@/components/EarningReports";
import OverallBalance from "@/components/OverallBalance";
import PaymentMethods from "@/components/PaymentMethods";
// import RecentProjects from "@/components/RecentProjects";
import ReturnOnInvest from "@/components/ReturnOnInvest";
import React from "react";
import type { Metadata } from "next";
import CardBox from "@/components/CardBox";
import Header from "@/app/(app)/Header"

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",

};

const Dashboard = () => {
  
  return (
    <>
<CardBox>

      <div className="grid grid-cols-12 gap-10">

      <Header title="Dashboard" />

        <div className="lg:col-span-8 col-span-12">
          {/* <OverallBalance /> */}
        </div>
        <div className="lg:col-span-4 col-span-12">
          {/* <ReturnOnInvest /> */}
        </div>
             
        <div className="col-span-12">
          {/* <RecentProjects /> */}
        </div>
        <div className="lg:col-span-8 col-span-12">
          {/* <DeliveryAnalytics /> */}
        </div>
        <div className="lg:col-span-4 col-span-12">
          {/* <EarningReports /> */}
        </div>
      </div>
      </CardBox>
    </>
  );
};
export default Dashboard;
